#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
if (int((ginp["islogin"] == "a"))): 
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "continer")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col l8 offset-l2 m10 offset-m1 s12")]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("account_admin");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_account_admin(cod([("users", ginp["users"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["account_admin"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
elif (int((int((ginp["islogin"] == "c")) or int((ginp["islogin"] == "u"))))): 
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "continer")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col s12 l6 m6")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("h3", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext("Change password");
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs(cod([("data", cod([("onsubmit", "sreq"), ("bobj", ""), ("action", "cpassword"), ("errorh", "error_login"), ("restext", "Changed!")]))]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("errorbox");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_errorbox(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["errorbox"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("input3");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_input3(cod([("label", "Old password"), ("aclass", "col s12 l12 m12"), ("name", "oldpass"), ("type", "password"), ("dc", "password1")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input3"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("input3");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_input3(cod([("label", "New password"), ("aclass", "col s12 l12 m12"), ("name", "newpass"), ("type", "password"), ("dc", "password1"), ("id", "password")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input3"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("input3");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_input3(cod([("label", "Repeat new password"), ("aclass", "col s12 l12 m12"), ("type", "password"), ("dc", "password")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input3"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("button", extentattrs(cod([("class", "btn waves-effect waves-light"), ("attr", cod([("type", "submit")]))]))));
  outpvar.cur.fcalldata["main2"].addtext("Change");
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", ["js/menu.js"]), ("htmlstyle", cod([("overflow-y", "scroll")]))]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);