#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height(cod([("val", 100)]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs(cod([("attr", cod([("enctype", "multipart/form-data"), ("method", "post")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("hidinp");
outpvar.cur.fcalldata["main2"].addchilds(newtag_hidinp(cod([("name", "dishid"), ("value", ginp["id"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["hidinp"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("hidinp");
outpvar.cur.fcalldata["main2"].addchilds(newtag_hidinp(cod([("name", "cid"), ("value", ginp["cid"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["hidinp"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input2(cod([("label", "Title of Dish"), ("aclass", "col s12 l4 m4"), ("id", "dishtitle"), ("value", ginp["title"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("input2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input2(cod([("label", "Price of Dish"), ("aclass", "col s12 l4 m4"), ("id", "dishprice"), ("value", ginp["price"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("select2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_select2(cod([("tlist", ginp["config"]["foodtype"].values()), ("dclass", "col l3 s12 m4"), ("class", "browser-default"), ("vlist", ginp["config"]["foodtype"].keys()), ("name", "isveg"), ("selected", ginp["isveg"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("textarea", extentattrs(cod([("class", "materialize-textarea"), ("attr", cod([("name", "descp"), ("placeholder", "Dish Description")]))]))));
outpvar.cur.fcalldata["main2"].addtext(ginp["descp"]);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext("If you upload newpic, oldpic will be overwritten");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "file-field input-field")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "btn")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].addtext("Upload Image");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("input", extentattrs(cod([("attr", cod([("type", "file"), ("name", "dishpic")]))]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "file-path-wrapper")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("input", extentattrs(cod([("class", "file-path-validate"), ("attr", cod([("type", "text")]))]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("button", extentattrs(cod([("class", "btn waves-effect waves-light"), ("attr", cod([("type", "submit"), ("name", "editdish")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Edit");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", [])]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);