#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("attr", cod([("id", "googlemap")]))]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "parallax-container"), ("id", "index-banner")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "section no-pad-bot")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container valign-wrapper"), ("style", cod([("height", "300px")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "valign"), ("style", cod([("width", "100%")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col l8 offset-l2 m12 s12")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "card-panel grey lighten-5 z-depth-1 "), ("attr", cod([("align", "center")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([("color", "black"), ("style", cod([("font-size", "25px")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Awesome Home Food");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([("color", "black"), ("style", cod([("font-size", "25px")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Near You");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("width", "20%"), ("border-bottom", "solid black 5px"), ("min-height", "2px"), ("margin-top", "10px"), ("margin-bottom", "10px")]))]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([("color", "black"), ("style", cod([("font-size", "16px")]))]))));
outpvar.cur.fcalldata["main2"].addtext("Fresh Ingredients, Daily Menus");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs(cod([("color", "black"), ("style", cod([("font-size", "16px")]))]))));
outpvar.cur.fcalldata["main2"].addtext("No Commitment, No Fuss");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "parallax")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("img", extentattrs(cod([("attr", cod([("alt", "Food"), ("src", "photo/pic_spice.jpg")]))]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container-fluid")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height(cod([("val", 30)]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "center")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv2(cod([("text", "HOW IT WORKS"), ("font", "30px"), ("fontw", None), ("style", cod([("font-family", "Gotham-Bold")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("width", "90%"), ("margin", "auto"), ("border-bottom", "solid #ccc 1px")]))]))));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height(cod([("val", 20)]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
hww_icons = ["photo/hww4_t.png", "photo/hww3_t.png", "photo/hww1_t.png", "photo/hww4_t.png"];
hww_texttitle = ["Search Kurrybox", "Chef Cooks", "Free Home Delivery"];
hww_texts = ["You search kurrybox.in and find who's cooking within 5 km of your current location & book a Meal.", "Our Awesome Home Chef cooks delicacy from her home kitchen.", "We do lightning fast free delivery in the slot you have selected"];
for i in forlist(3, False ) :
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col l4 m4 s12 center"), ("style", cod([("padding-top", "10px")]))]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("resimg");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_resimg(cod([("src", hww_icons[i])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["resimg"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv2");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv2(cod([("text", hww_texttitle[i]), ("font", "20px")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv2"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("padding", "10px")]))]))));
  outpvar.cur.fcalldata["main2"].addtext(hww_texts[i]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height(cod([("val", 50)]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("footer1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_footer1(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["footer1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "contactusform"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("contactus_form");
outpvar.cur.fcalldata["main2"].addchilds(newtag_contactus_form(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["contactus_form"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", ["js/index.js?reload"])]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);