#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main_rec");
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("width", "680px"), ("overflow", "hidden"), ("margin", "auto"), ("border", "solid #ccc 1px")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("height", "180px;"), ("overflow", "hidden")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("img", extentattrs(cod([("attr", cod([("src", myadd(ginp["HOST"], "photo/recipt/photo3.png"))]))]))));
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("float", "left"), ("width", "50%")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("margin-left", "30px"), ("margin-top", "60px")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("b", extentattrs(cod([("style", cod([("font-size", "20px"), ("color", "#26A69A")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext(myadd(ginp["uname"], ","));
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("span", extentattrs(cod([("style", cod([("font-size", "18px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Thank You for shopping at kurrybox.in");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("b", extentattrs(cod([("style", cod([("font-size", "18px"), ("color", "#26A69A")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Your Order Will be Delivered At: ");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("i", extentattrs(cod([("style", cod([("font-size", "15px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext(ginp["address"]);
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].addtext("Phone: ");
outpvar.cur.fcalldata["main_rec"].addtext(ginp["phone"]);
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("float", "left"), ("width", "50%")])), ("attr", cod([("align", "right")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("margin-right", "30px"), ("margin-top", "20px")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("margin-right", "10px")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("img", extentattrs(cod([("attr", cod([("src", myadd(ginp["HOST"], "photo/logo4.png"))]))]))));
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("table", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("tr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("font-weight", 900), ("font-size", "18px"), ("color", "#26A69A"), ("padding", "5px")])), ("attr", cod([("align", "right"), ("valign", "top")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Orderd At: ");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("font-size", "18px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext(ginp["orderedat"]);
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("tr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("font-weight", 900), ("font-size", "18px"), ("color", "#26A69A"), ("padding", "5px")])), ("attr", cod([("align", "right")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Order ID: ");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("font-size", "18px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext(ginp["uorderid"]);
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("tr", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("font-weight", 900), ("font-size", "18px"), ("color", "#26A69A"), ("padding", "5px")])), ("attr", cod([("align", "right")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Payment ID: ");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("font-size", "18px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext(ginp["paymentid"]);
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("clear", "both")]))]))));
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("margin", "30px"), ("margin-top", "10px")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("table", extentattrs(cod([("attr", cod([("cellspacing", "0"), ("cellpadding", "0"), ("border", 0)]))]))));
width = [10, 280, 200, 80, 80];
outpvar.cur.fcalldata["main_rec"].open(htmlnode("tr", extentattrs(cod([]))));
titles = ["S.No.", "Dish", "Due On", "Price*Qty", "Amount"];
for ii in forlist(titles, True ) :
  i = titles[ii];
  outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("padding", "15px 3px"), ("border", "solid #26A69A 1px"), ("margin", "0px"), ("background-color", "#26A69A"), ("color", "white"), ("font-weight", 900)])), ("attr", cod([("align", "center")]))]))));
  outpvar.cur.fcalldata["main_rec"].addtext(i);
  outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
for jj in forlist(ginp["olist"], True ) :
  j = ginp["olist"][jj];
  outpvar.cur.fcalldata["main_rec"].open(htmlnode("tr", extentattrs(cod([]))));
  titles = [myadd(jj, 1), myadd(myadd(myadd("<b>", j["dishtitle"]), "</b><br>From Chef "), j["chefname"]), j["dueon"], myadd(myadd(j["price"], "*"), j["numplate"]), (j["price"] * j["numplate"])];
  for ii in forlist(titles, True ) :
    i = titles[ii];
    outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("padding", "15px 3px"), ("border", "solid #26A69A 1px"), ("margin", "0px"), ("width", myadd(width[ii], "px"))])), ("attr", cod([("align", "center")]))]))));
    outpvar.cur.fcalldata["main_rec"].addtext(i);
    outpvar.cur.fcalldata["main_rec"].close();
  outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
if (int((ginp["discount"] != None))): 
  outpvar.cur.fcalldata["main_rec"].open(htmlnode("table", extentattrs(cod([("attr", cod([("cellspacing", "0"), ("cellpadding", "0"), ("border", 0)]))]))));
  width = [myadd(myadd(myadd(10, 280), 250), 20), 80];
  elms = [[myadd("Total Amount: ", ("&nbsp;" * 2)), myadd("Discount: ", ("&nbsp;" * 2))], [ginp["totalamount"], myadd("-", ginp["discount"])]];
  for j in forlist(2, False ) :
    outpvar.cur.fcalldata["main_rec"].open(htmlnode("tr", extentattrs(cod([]))));
    for i in forlist(2, False ) :
      outpvar.cur.fcalldata["main_rec"].open(htmlnode("td", extentattrs(cod([("style", cod([("padding", "10px 3px"), ("border", "solid #26A69A 1px"), ("margin", "0px"), ("width", myadd(width[i], "px")), ("font-weight", "800")])), ("attr", cod([("align", ["right", "center"][i])]))]))));
      outpvar.cur.fcalldata["main_rec"].addtext(elms[i][j]);
      outpvar.cur.fcalldata["main_rec"].close();
    outpvar.cur.fcalldata["main_rec"].close();
  outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("attr", cod([("align", "right")])), ("style", cod([("background-color", "#26A69A")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("padding", "20px 10px"), ("color", "white"), ("font-weight", 900)]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("b", extentattrs(cod([("style", cod([("font-size", "30px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Total Payment:");
outpvar.cur.fcalldata["main_rec"].addtext(("&nbsp;" * 5));
outpvar.cur.fcalldata["main_rec"].addtext(" Rs. ");
outpvar.cur.fcalldata["main_rec"].addtext(ginp["amount"]);
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("b", extentattrs(cod([("style", cod([("font-size", "25px"), ("color", "#26A69A")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Enjoy your meal");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("i", extentattrs(cod([("style", cod([("font-size", "20px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Kurrybox Team");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("br", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("span", extentattrs(cod([("style", cod([("font-size", "20px")]))]))));
outpvar.cur.fcalldata["main_rec"].addtext("Contactus@kurrybox.in");
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].open(htmlnode("div", extentattrs(cod([("style", cod([("height", "180px;"), ("overflow", "hidden")]))]))));
outpvar.cur.fcalldata["main_rec"].open(htmlnode("img", extentattrs(cod([("attr", cod([("src", myadd(ginp["HOST"], "photo/recipt/photo4.png"))]))]))));
outpvar.cur.fcalldata["main_rec"].close();
outpvar.cur.fcalldata["main_rec"].close();
outpvar.addchilds(newtag_main_rec(cod([]), ginp, outpvar.cur.fcalldata["main_rec"].root.content).root.content);