#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container-fluid")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv(cod([("text", "Transactions"), ("class", "bigtext")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("button2");
outpvar.cur.fcalldata["main2"].addchilds(newtag_button2(cod([("text", "Export"), ("attr", cod([("type", "button")])), ("data", cod([("onclick", "sreq"), ("action", "export_transc"), ("res", "ms.exportp(data);")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button2"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("table", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("thead", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("tr", extentattrs(cod([]))));
for i in forlist(["PaymentID", "Price Amount", "Discount", "Amount Paid", "PayuMoneyID", "Bank_Ref_Num", "txnid", "Bank", "Order IDs", "Reciept"], False ) :
  outpvar.cur.fcalldata["main2"].open(htmlnode("th", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i);
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("tbody", extentattrs(cod([]))));
for ii in forlist(ginp["uorders"], True ) :
  i = ginp["uorders"][ii];
  outpvar.cur.fcalldata["main2"].open(htmlnode("tr", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i["id"]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(myadd("Rs. ", i["price_amount"]));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(myadd("Rs. ", i["discount"]));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(myadd("Rs. ", i["net_amount_debit"]));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i["payuMoneyId"]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i["bank_ref_num"]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i["txnid"]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i["bankcode"]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].addtext(i["orderids"]);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("a1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_a1(cod([("href", myadd(ginp["HOST"], i["reciptfile"])), ("text", "Reciept")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["a1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("a1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_a1(cod([("href", myadd(ginp["HOST"], i["reciptpdf"])), ("text", "RecieptPdf")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["a1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", []), ("htmlstyle", cod([]))]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);